//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ENT_Interface.Entity
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ENTEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ENTEntities object using the connection string found in the 'ENTEntities' section of the application configuration file.
        /// </summary>
        public ENTEntities() : base("name=ENTEntities", "ENTEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ENTEntities object.
        /// </summary>
        public ENTEntities(string connectionString) : base(connectionString, "ENTEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ENTEntities object.
        /// </summary>
        public ENTEntities(EntityConnection connection) : base(connection, "ENTEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cash> Cash
        {
            get
            {
                if ((_Cash == null))
                {
                    _Cash = base.CreateObjectSet<Cash>("Cash");
                }
                return _Cash;
            }
        }
        private ObjectSet<Cash> _Cash;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CashHeading> CashHeading
        {
            get
            {
                if ((_CashHeading == null))
                {
                    _CashHeading = base.CreateObjectSet<CashHeading>("CashHeading");
                }
                return _CashHeading;
            }
        }
        private ObjectSet<CashHeading> _CashHeading;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Customer> Customer
        {
            get
            {
                if ((_Customer == null))
                {
                    _Customer = base.CreateObjectSet<Customer>("Customer");
                }
                return _Customer;
            }
        }
        private ObjectSet<Customer> _Customer;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Good> Good
        {
            get
            {
                if ((_Good == null))
                {
                    _Good = base.CreateObjectSet<Good>("Good");
                }
                return _Good;
            }
        }
        private ObjectSet<Good> _Good;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Shop> Shop
        {
            get
            {
                if ((_Shop == null))
                {
                    _Shop = base.CreateObjectSet<Shop>("Shop");
                }
                return _Shop;
            }
        }
        private ObjectSet<Shop> _Shop;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cash EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCash(Cash cash)
        {
            base.AddObject("Cash", cash);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CashHeading EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCashHeading(CashHeading cashHeading)
        {
            base.AddObject("CashHeading", cashHeading);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Customer EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCustomer(Customer customer)
        {
            base.AddObject("Customer", customer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Good EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGood(Good good)
        {
            base.AddObject("Good", good);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Shop EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToShop(Shop shop)
        {
            base.AddObject("Shop", shop);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ENTModel", Name="Cash")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cash : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cash object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="id_good">Initial value of the Id_good property.</param>
        /// <param name="id_cashheading">Initial value of the Id_cashheading property.</param>
        public static Cash CreateCash(global::System.Int32 id, global::System.Int32 id_good, global::System.Int32 id_cashheading)
        {
            Cash cash = new Cash();
            cash.Id = id;
            cash.Id_good = id_good;
            cash.Id_cashheading = id_cashheading;
            return cash;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_good
        {
            get
            {
                return _Id_good;
            }
            set
            {
                if (_Id_good != value)
                {
                    OnId_goodChanging(value);
                    ReportPropertyChanging("Id_good");
                    _Id_good = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id_good");
                    OnId_goodChanged();
                }
            }
        }
        private global::System.Int32 _Id_good;
        partial void OnId_goodChanging(global::System.Int32 value);
        partial void OnId_goodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_cashheading
        {
            get
            {
                return _Id_cashheading;
            }
            set
            {
                if (_Id_cashheading != value)
                {
                    OnId_cashheadingChanging(value);
                    ReportPropertyChanging("Id_cashheading");
                    _Id_cashheading = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id_cashheading");
                    OnId_cashheadingChanged();
                }
            }
        }
        private global::System.Int32 _Id_cashheading;
        partial void OnId_cashheadingChanging(global::System.Int32 value);
        partial void OnId_cashheadingChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ENTModel", Name="CashHeading")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CashHeading : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CashHeading object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="id_customer">Initial value of the Id_customer property.</param>
        /// <param name="id_shop">Initial value of the Id_shop property.</param>
        public static CashHeading CreateCashHeading(global::System.Int32 id, global::System.Int32 id_customer, global::System.Int32 id_shop)
        {
            CashHeading cashHeading = new CashHeading();
            cashHeading.Id = id;
            cashHeading.Id_customer = id_customer;
            cashHeading.Id_shop = id_shop;
            return cashHeading;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_customer
        {
            get
            {
                return _Id_customer;
            }
            set
            {
                if (_Id_customer != value)
                {
                    OnId_customerChanging(value);
                    ReportPropertyChanging("Id_customer");
                    _Id_customer = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id_customer");
                    OnId_customerChanged();
                }
            }
        }
        private global::System.Int32 _Id_customer;
        partial void OnId_customerChanging(global::System.Int32 value);
        partial void OnId_customerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_shop
        {
            get
            {
                return _Id_shop;
            }
            set
            {
                if (_Id_shop != value)
                {
                    OnId_shopChanging(value);
                    ReportPropertyChanging("Id_shop");
                    _Id_shop = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id_shop");
                    OnId_shopChanged();
                }
            }
        }
        private global::System.Int32 _Id_shop;
        partial void OnId_shopChanging(global::System.Int32 value);
        partial void OnId_shopChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date;
        partial void OnDateChanging(Nullable<global::System.DateTime> value);
        partial void OnDateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ENTModel", Name="Customer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Customer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Customer object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Customer CreateCustomer(global::System.Int32 id)
        {
            Customer customer = new Customer();
            customer.Id = id;
            return customer;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ENTModel", Name="Good")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Good : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Good object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Good CreateGood(global::System.Int32 id)
        {
            Good good = new Good();
            good.Id = id;
            return good;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Article
        {
            get
            {
                return _Article;
            }
            set
            {
                OnArticleChanging(value);
                ReportPropertyChanging("Article");
                _Article = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Article");
                OnArticleChanged();
            }
        }
        private global::System.String _Article;
        partial void OnArticleChanging(global::System.String value);
        partial void OnArticleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Material
        {
            get
            {
                return _Material;
            }
            set
            {
                OnMaterialChanging(value);
                ReportPropertyChanging("Material");
                _Material = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Material");
                OnMaterialChanged();
            }
        }
        private global::System.String _Material;
        partial void OnMaterialChanging(global::System.String value);
        partial void OnMaterialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Color
        {
            get
            {
                return _Color;
            }
            set
            {
                OnColorChanging(value);
                ReportPropertyChanging("Color");
                _Color = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Color");
                OnColorChanged();
            }
        }
        private global::System.String _Color;
        partial void OnColorChanging(global::System.String value);
        partial void OnColorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private Nullable<global::System.Int32> _Price;
        partial void OnPriceChanging(Nullable<global::System.Int32> value);
        partial void OnPriceChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ENTModel", Name="Shop")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Shop : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Shop object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Shop CreateShop(global::System.Int32 id)
        {
            Shop shop = new Shop();
            shop.Id = id;
            return shop;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Shop1
        {
            get
            {
                return _Shop1;
            }
            set
            {
                OnShop1Changing(value);
                ReportPropertyChanging("Shop1");
                _Shop1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Shop1");
                OnShop1Changed();
            }
        }
        private global::System.String _Shop1;
        partial void OnShop1Changing(global::System.String value);
        partial void OnShop1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();

        #endregion

    
    }

    #endregion

    
}
